version: '3'
services:
  everyonetoday-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234!
      - POSTGRES_USER=user
      - POSTGRES_DB=posts
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
